builds:
  - id: benthos
    main: cmd/benthos/main.go
    binary: benthos
    goos: [ windows, linux ]
    goarch: [ amd64 ]
    ignore:
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
    env:
      - CGO_ENABLED=0
    ldflags: >
      -s -w
      -X github.com/benthosdev/benthos/v4/internal/cli.Version={{.Version}}
      -X github.com/benthosdev/benthos/v4/internal/cli.DateBuilt={{.Date}}
archives:
  - id: benthos
    builds: [ benthos ]
    format: tar.gz
    files:
      - README.md
      - CHANGELOG.md
      - LICENSE
dist: target/dist
release:
  github:
    owner: benthosdev
    name: benthos
  prerelease: auto
  disable: false
