version: '3.3'
services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda
    ports:
      - 8081:8081
    command:
      - 'redpanda start'
      - '--smp 1'
      - '--overprovisioned'
      - '--kafka-addr 0.0.0.0:9092'
      - '--advertise-kafka-addr redpanda:9092'
      - '--pandaproxy-addr 0.0.0.0:8082'
      - '--advertise-pandaproxy-addr redpanda:8082'

  benthos-in:
    image: ghcr.io/benthosdev/benthos
    command: [ '-w', '-c', '/benthos.yaml' ]
    volumes:
      - ./in.yaml:/benthos.yaml

  benthos-out:
    image: ghcr.io/benthosdev/benthos
    command: [ '-w', '-c', '/benthos.yaml' ]
    volumes:
      - ./out.yaml:/benthos.yaml
