version: '3.3'
services:
  benthos:
    image: ghcr.io/benthosdev/benthos
    command: [ '-c', '/benthos.yaml', 'streams', '/streams/*.yaml' ]
    volumes:
      - ./benthos.yaml:/benthos.yaml
      - ./streams:/streams
